language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - source setup/setup.sh

#services:
#  - mysql
#
#before_script:
#  - mysql -e 'create database myapp_test'
#  - mysql -e 'show databases;'

script:
  - nosetests -s --with-coverage --cover-package=dateconvert
  - pylint --py3k `find . -name \*.py -print`

after_success:
  - coveralls
